In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np

In [11]:
my_list= [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
type(my_list)

list

below cord we are converting list to array


In [13]:
arr= np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(my_list)

list

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [22]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(20,10)

array([], dtype=int64)

In [25]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [26]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])